---
server:
  port: $!{port}
spring:
  cloud:
   config:
     server:
       git:
         uri: $!{gitUri}
         #username: $!{gitUsername}
         #password: $!{gitPassword}
  security:
   path: /**
   user: 
     name: scott
     password: tiger
      

