---
server:
  port: $!{port}
spring:
  cloud:
   config:
     server:
       git:
         uri: $!{gitUri}
         #username: $!{configUsername}
         #password: $!{configUsername}
  security:
   path: /**
   user: 
     name: $!{configUsername}
     password: $!{configPassword}
      

